# @format

name: Build and Deploy Source Documentation with Doxygen

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (main)
        uses: actions/checkout@v2

      - name: Checkout (documentation)
        uses: actions/checkout@v2
        with:
          ref: documentation
          path: documentation/doxygen

      - name: Setup Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          cache: 'npm'

      - run: npm ci
      - run: npm run docs

      - uses: EndBug/add-and-commit@7
        with:
          add: .
          cwd: documentation/doxygen
          message: 'chore: freshen up documentation'
