# @format

name: Build and Deploy Source Documentation with Doxygen

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (main)
        uses: actions/checkout@v2

      - name: Checkout (documentation)
        uses: actions/checkout@v2
        with:
          ref: documentation
          path: documentation/doxygen

      - name: Build Doxygen
        uses: mattnotmitt/doxygen-action@v1
        with:
          doxyfile-path: './doxyfile'

      - name: Like, totally like submit the fresh new stuff like, you know
        uses: EndBug/add-and-commit@v7
        with:
          add: .
          cwd: documentation/doxygen
          message: 'chore: freshen up documentation'
          author_name: Lumpy Space Princess
          author_email: buttercup.rules.xxx@lumpy.space
